[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_strike = "F7Dr4bH5knKjzBj8fuRJT9QGtHLyQSWTnWxYetHDnWHA"

[programs.devnet]
sol_strike = "F7Dr4bH5knKjzBj8fuRJT9QGtHLyQSWTnWxYetHDnWHA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
get-pdas = "npx ts-node scripts/get-pdas.ts"
init = "npx ts-node scripts/init.ts"
buy-and-reserve = "npx ts-node scripts/buy-and-reserve.ts"
decode-log = "npx ts-node scripts/decode-log.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true
